apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-tutorial
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: node-tutorial
    spec:
      containers:
        - name: node-tutorial
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM
          args:
            - npm
            - run
            - start
          env:
          ports:
            - containerPort: 3000
