apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-tutorial
  name: node-tutorial
spec:
  ports:
    # The port that this service should serve on.
    - port: 80
      targetPort: 3000
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    run: node-tutorial
  type: LoadBalancer
